#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 8

# Update package index
apt-get update

# Install nginx
apt-get install -y nginx

# Configure nginx to listen on port 80 and return "Hello World!" at root
echo "Hello World!" > /var/www/html/index.html

# Replace default nginx configuration to listen on port 80
sed -i 's/80 default_server;/80;/g' /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
